package com.hook38.sporttimer.model.sql;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.IdentityScopeType;

import com.hook38.sporttimer.model.sql.RoutineSQL;
import com.hook38.sporttimer.model.sql.TimeUnitSQL;

import com.hook38.sporttimer.model.sql.RoutineSQLDao;
import com.hook38.sporttimer.model.sql.TimeUnitSQLDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig routineSQLDaoConfig;
    private final DaoConfig timeUnitSQLDaoConfig;

    private final RoutineSQLDao routineSQLDao;
    private final TimeUnitSQLDao timeUnitSQLDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        routineSQLDaoConfig = daoConfigMap.get(RoutineSQLDao.class).clone();
        routineSQLDaoConfig.initIdentityScope(type);

        timeUnitSQLDaoConfig = daoConfigMap.get(TimeUnitSQLDao.class).clone();
        timeUnitSQLDaoConfig.initIdentityScope(type);

        routineSQLDao = new RoutineSQLDao(routineSQLDaoConfig, this);
        timeUnitSQLDao = new TimeUnitSQLDao(timeUnitSQLDaoConfig, this);

        registerDao(RoutineSQL.class, routineSQLDao);
        registerDao(TimeUnitSQL.class, timeUnitSQLDao);
    }
    
    public void clear() {
        routineSQLDaoConfig.getIdentityScope().clear();
        timeUnitSQLDaoConfig.getIdentityScope().clear();
    }

    public RoutineSQLDao getRoutineSQLDao() {
        return routineSQLDao;
    }

    public TimeUnitSQLDao getTimeUnitSQLDao() {
        return timeUnitSQLDao;
    }

}
